### PR TITLE
Readme for Mac

### PR DESCRIPTION
**Pull request by ECiurleo**
Instructions on how to setup and run a local development env on an M1 Mac using Brew

### CODE REVIEW

**Comment by gmkurtzer** [comment]
Any reason not to use the source based installation directly, as it works for almost everything once GoLang is installed:

```
CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest
hugo version
```

**Comment by ECiurleo** [comment]
The above didn't work out of the box for me on my M1 and required installing the dependencies manually anyway.  My machine was pretty vanilla at that point
So really my logic for using Brew was just to keep the setup mechanism very simple and consistent.

**Comment by gmkurtzer** [comment]
Oh, that's interesting... That's exactly what I did for my M1, granted I did need Git, which is provided via:

```
xcode-select --install
```

I like doing it that way personally myself, but maybe to make it easier, we just link to the Hugo installation install page directly?

**Comment by ECiurleo** [comment]
Happy to go either way tbh, but my only query is that the latest Hugo version was breaking compared to what was in certain distro Repos .

If the intention is to remain bleeding edge, then a link to Hugo makes most sense. (v115) 

If the intention is to build off/around a specific version then brew does (v111) - this happens to be the same on Fedora Rawhide

**Comment by NeilHanlon** [comment]
Hi - I wanted to check in and see what we can do for next steps on this, if any are required. 

Unfortunately, I don't have a mac to test with at this time, but, I think we can handle this generally under developer experience overall to work with this repo, as well as commit changes, etc.

**Comment by ECiurleo** [comment]
I don't think much more is needed here beyond a review.  I am personally a fan of the readme getting people up and running asap in a consistent way, hence the contribution.  However if you feel its not required, then that's also cool.

**Review by gmkurtzer — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
